In [52]:
from PIL import Image
import os
# import cv2
import numpy as np

In [53]:
def load_images_from_folder(folder):
    pix_val = []
    for filename in os.listdir(folder):
        print(filename)
        img = Image.open(folder+filename)        
        if img is not None:
            pix = list(img.getdata())
            pix_val.append(pix)
        img.close()
    return pix_val

In [54]:
# im = Image.open(r"/Users/linjian/Documents/coil-100/obj1__0.png")
folder = "/Users/linjian/Documents/coil-100/"
pix_val = load_images_from_folder(folder)

obj82__35.png
obj89__90.png
obj8__240.png
obj66__20.png
obj17__220.png
obj30__170.png
obj44__320.png
obj28__355.png
obj99__90.png
obj92__35.png
obj29__355.png
obj16__220.png
obj45__320.png
obj31__170.png
obj9__240.png
obj76__20.png
obj17__40.png
obj33__5.png
obj1__85.png
obj20__265.png
obj21__265.png
obj94__70.png
obj53__285.png
obj59__325.png
obj93__150.png
obj21__95.png
obj41__100.png
obj35__350.png
obj66__250.png
obj70__65.png
obj52__285.png
obj31__95.png
obj34__350.png
obj40__100.png
obj67__250.png
obj58__325.png
obj92__150.png
obj84__70.png
obj40__0.png
obj60__65.png
obj43__190.png
obj83__245.png
obj51__215.png
obj76__145.png
obj5__150.png
obj4__150.png
obj42__190.png
obj50__215.png
obj77__145.png
obj82__245.png
obj98__95.png
obj6__315.png
obj75__300.png
obj26__200.png
obj98__225.png
obj93__30.png
obj34__185.png
obj77__25.png
obj83__30.png
obj74__300.png
obj27__200.png
obj99__225.png
obj35__185.png
obj88__95.png
obj7__315.png
obj67__25.png
obj11__245.png
obj88__130.png
obj42__345.

obj22__180.png
obj63__305.png
obj17__155.png
obj30__205.png
obj8__135.png
obj64__85.png
obj33__295.png
obj87__310.png
obj39__335.png
obj55__340.png
obj21__110.png
obj54__15.png
obj44__15.png
obj8__85.png
obj32__295.png
obj3__20.png
obj20__110.png
obj54__340.png
obj86__310.png
obj38__335.png
obj38__95.png
obj40__275.png
obj67__125.png
obj33__30.png
obj92__225.png
obj69__65.png
obj93__225.png
obj41__275.png
obj23__30.png
obj66__125.png
obj28__95.png
obj79__65.png
obj24__330.png
obj50__160.png
obj77__230.png
obj48__345.png
obj82__130.png
obj4__225.png
obj5__65.png
obj42__50.png
obj5__225.png
obj49__345.png
obj83__130.png
obj51__160.png
obj25__330.png
obj76__230.png
obj52__50.png
obj34__70.png
obj81__95.png
obj99__150.png
obj27__175.png
obj53__325.png
obj59__285.png
obj65__80.png
obj98__150.png
obj52__325.png
obj26__175.png
obj91__95.png
obj58__285.png
obj24__70.png
obj75__80.png
obj10__130.png
obj37__260.png
obj89__245.png
obj49__190.png
obj9__80.png
obj100__95.png
obj45__10.png
obj2__25.

obj22__345.png
obj84__145.png
obj39__80.png
obj32__25.png
obj45__290.png
obj85__145.png
obj70__245.png
obj23__345.png
obj57__115.png
obj68__70.png
obj3__250.png
obj54__185.png
obj53__45.png
obj15__300.png
obj61__150.png
obj46__200.png
obj94__250.png
obj95__0.png
obj19__10.png
obj4__70.png
obj55__185.png
obj95__250.png
obj60__150.png
obj43__45.png
obj14__300.png
obj47__200.png
obj34__60.png
obj59__295.png
obj81__85.png
obj99__140.png
obj27__165.png
obj53__335.png
obj65__90.png
obj58__295.png
obj98__140.png
obj52__335.png
obj26__165.png
obj91__85.png
obj24__60.png
obj75__90.png
obj49__180.png
obj37__270.png
obj89__255.png
obj10__120.png
obj100__85.png
obj9__90.png
obj2__35.png
obj48__180.png
obj36__270.png
obj88__255.png
obj11__120.png
obj38__85.png
obj67__135.png
obj33__20.png
obj40__265.png
obj92__235.png
obj69__75.png
obj93__235.png
obj23__20.png
obj66__135.png
obj41__265.png
obj28__85.png
obj79__75.png
obj77__220.png
obj24__320.png
obj50__170.png
obj48__355.png
obj82__120.png
obj85__

obj38__45.png
obj6__265.png
obj59__25.png
obj52__80.png
obj43__235.png
obj64__165.png
obj10__335.png
obj91__265.png
obj42__80.png
obj3__5.png
obj49__25.png
obj90__265.png
obj42__235.png
obj11__335.png
obj13__70.png
obj65__165.png
obj30__80.png
obj85__65.png
obj3__125.png
obj61__70.png
obj29__190.png
obj68__315.png
obj85__230.png
obj70__130.png
obj57__260.png
obj95__65.png
obj20__80.png
obj28__190.png
obj71__70.png
obj71__130.png
obj56__260.png
obj69__315.png
obj84__230.png
obj2__125.png
obj10__10.png
obj39__285.png
obj95__125.png
obj60__225.png
obj33__325.png
obj47__175.png
obj38__285.png
obj61__225.png
obj46__175.png
obj32__325.png
obj94__125.png
obj6__305.png
obj98__85.png
obj34__195.png
obj26__210.png
obj98__235.png
obj75__310.png
obj93__20.png
obj77__35.png
obj35__195.png
obj83__20.png
obj27__210.png
obj99__235.png
obj74__310.png
obj7__305.png
obj88__85.png
obj76__5.png
obj67__35.png
obj78__0.png
obj24__280.png
obj88__120.png
obj42__355.png
obj36__105.png
obj11__255.png
obj90__305.

obj31__110.png
obj45__340.png
obj82__55.png
obj72__5.png
obj22__295.png
obj17__240.png
obj44__340.png
obj30__110.png
obj96__310.png
obj28__335.png
obj8__220.png
obj66__40.png
obj33__180.png
obj72__305.png
obj21__205.png
obj1__310.png
obj17__20.png
obj32__180.png
obj73__305.png
obj20__205.png
obj5__0.png
obj84__10.png
obj40__160.png
obj34__330.png
obj67__230.png
obj58__345.png
obj92__130.png
obj59__345.png
obj93__130.png
obj35__330.png
obj41__160.png
obj66__230.png
obj94__10.png
obj11__65.png
obj50__275.png
obj77__125.png
obj82__225.png
obj4__130.png
obj40__95.png
obj5__130.png
obj83__225.png
obj51__275.png
obj76__125.png
obj50__95.png
obj83__50.png
obj18__315.png
obj27__260.png
obj99__245.png
obj59__190.png
obj62__0.png
obj67__45.png
obj26__260.png
obj98__245.png
obj93__50.png
obj19__315.png
obj58__190.png
obj77__45.png
obj10__225.png
obj89__150.png
obj43__325.png
obj37__175.png
obj49__285.png
obj16__25.png
obj11__225.png
obj88__150.png
obj36__175.png
obj42__325.png
obj48__285.png
obj9

obj96__70.png
obj72__65.png
obj78__115.png
obj33__230.png
obj14__160.png
obj60__330.png
obj13__5.png
obj15__40.png
obj8__20.png
obj3__85.png
obj32__230.png
obj61__330.png
obj15__160.png
obj79__115.png
obj90__35.png
obj74__20.png
obj9__190.png
obj85__325.png
obj68__200.png
obj23__125.png
obj80__35.png
obj22__125.png
obj84__325.png
obj69__200.png
obj64__20.png
obj8__190.png
obj73__260.png
obj54__130.png
obj86__160.png
obj38__145.png
obj58__55.png
obj48__55.png
obj100__105.png
obj1__275.png
obj87__160.png
obj39__145.png
obj72__260.png
obj55__130.png
obj7__0.png
obj22__90.png
obj97__75.png
obj9__5.png
obj29__35.png
obj8__345.png
obj73__60.png
obj17__325.png
obj63__175.png
obj44__225.png
obj28__250.png
obj96__275.png
obj87__75.png
obj39__35.png
obj32__90.png
obj29__250.png
obj97__275.png
obj62__175.png
obj63__60.png
obj16__325.png
obj70__5.png
obj45__225.png
obj9__345.png
obj49__135.png
obj83__340.png
obj25__140.png
obj51__310.png
obj10__195.png
obj14__45.png
obj100__30.png
obj9__25.png
obj

obj60__130.png
obj47__260.png
obj4__10.png
obj48__80.png
obj58__80.png
obj38__190.png
obj61__130.png
obj53__25.png
obj46__260.png
obj79__315.png
obj94__230.png
obj34__280.png
obj98__120.png
obj26__105.png
obj52__355.png
obj80__305.png
obj35__280.png
obj81__305.png
obj99__120.png
obj53__355.png
obj27__105.png
obj24__195.png
obj36__210.png
obj88__235.png
obj65__310.png
obj11__140.png
obj55__60.png
obj14__90.png
obj25__195.png
obj37__210.png
obj89__235.png
obj10__140.png
obj64__310.png
obj2__55.png
obj45__60.png
obj93__255.png
obj66__155.png
obj12__305.png
obj23__40.png
obj41__205.png
obj53__180.png
obj79__15.png
obj13__305.png
obj33__40.png
obj67__155.png
obj40__205.png
obj92__255.png
obj52__180.png
obj69__15.png
obj49__335.png
obj83__140.png
obj76__240.png
obj25__340.png
obj51__110.png
obj43__295.png
obj5__255.png
obj59__85.png
obj52__20.png
obj4__255.png
obj18__75.png
obj77__240.png
obj50__110.png
obj24__340.png
obj48__335.png
obj82__140.png
obj42__295.png
obj42__20.png
obj49__85.png
o

obj46__330.png
obj32__160.png
obj79__245.png
obj46__30.png
obj68__150.png
obj23__275.png
obj27__50.png
obj99__10.png
obj22__275.png
obj69__150.png
obj37__50.png
obj89__10.png
obj40__75.png
obj7__40.png
obj11__85.png
obj42__110.png
obj36__340.png
obj65__240.png
obj90__140.png
obj50__295.png
obj50__75.png
obj91__140.png
obj37__340.png
obj43__110.png
obj64__240.png
obj51__295.png
obj52__205.png
obj75__155.png
obj80__255.png
obj19__120.png
obj40__180.png
obj31__15.png
obj6__140.png
obj7__140.png
obj81__255.png
obj18__120.png
obj53__205.png
obj74__155.png
obj41__180.png
obj21__15.png
obj69__185.png
obj17__275.png
obj30__125.png
obj96__325.png
obj28__300.png
obj8__215.png
obj66__75.png
obj37__85.png
obj2__0.png
obj82__60.png
obj9__215.png
obj76__75.png
obj68__185.png
obj97__325.png
obj29__300.png
obj16__275.png
obj31__125.png
obj92__60.png
obj27__85.png
obj79__290.png
obj73__330.png
obj20__230.png
obj75__5.png
obj17__15.png
obj78__290.png
obj72__330.png
obj21__230.png
obj1__325.png
obj70__30

obj2__165.png
obj84__270.png
obj69__355.png
obj56__220.png
obj71__170.png
obj71__30.png
obj59__65.png
obj91__225.png
obj64__125.png
obj43__275.png
obj49__65.png
obj67__0.png
obj13__30.png
obj65__125.png
obj42__275.png
obj90__225.png
obj18__95.png
obj69__5.png
obj72__50.png
obj18__245.png
obj81__130.png
obj74__230.png
obj99__315.png
obj27__330.png
obj53__160.png
obj7__225.png
obj96__45.png
obj62__50.png
obj6__225.png
obj86__45.png
obj75__230.png
obj98__315.png
obj52__160.png
obj26__330.png
obj19__245.png
obj80__130.png
obj8__15.png
obj44__85.png
obj20__180.png
obj32__205.png
obj15__155.png
obj61__305.png
obj79__120.png
obj15__75.png
obj21__180.png
obj78__120.png
obj33__205.png
obj60__305.png
obj14__155.png
obj54__85.png
obj30__295.png
obj56__340.png
obj22__110.png
obj84__310.png
obj14__5.png
obj69__235.png
obj64__15.png
obj74__15.png
obj31__295.png
obj85__310.png
obj68__235.png
obj23__110.png
obj57__340.png
obj48__60.png
obj100__130.png
obj1__240.png
obj87__155.png
obj39__170.png
obj72_

obj63__80.png
obj62__195.png
obj97__295.png
obj85__110.png
obj70__210.png
obj23__310.png
obj57__140.png
obj32__70.png
obj87__95.png
obj86__180.png
obj73__280.png
obj15__355.png
obj53__10.png
obj61__105.png
obj46__255.png
obj79__320.png
obj94__205.png
obj72__280.png
obj87__180.png
obj78__320.png
obj95__205.png
obj60__105.png
obj14__355.png
obj43__10.png
obj47__255.png
obj4__25.png
obj1__295.png
obj19__45.png
obj81__330.png
obj99__115.png
obj27__130.png
obj34__35.png
obj24__35.png
obj98__115.png
obj26__130.png
obj80__330.png
obj2__60.png
obj45__55.png
obj37__225.png
obj89__200.png
obj64__325.png
obj10__175.png
obj55__55.png
obj36__225.png
obj88__200.png
obj11__175.png
obj65__325.png
obj69__20.png
obj62__85.png
obj67__160.png
obj13__330.png
obj33__75.png
obj40__230.png
obj92__260.png
obj19__290.png
obj86__90.png
obj72__85.png
obj79__20.png
obj96__90.png
obj93__260.png
obj12__330.png
obj23__75.png
obj66__160.png
obj41__230.png
obj18__290.png
obj42__15.png
obj5__20.png
obj4__260.png
obj18__

obj8__0.png
obj99__205.png
obj27__220.png
obj74__320.png
obj18__355.png
obj83__10.png
obj7__335.png
obj6__5.png
obj6__335.png
obj19__355.png
obj93__10.png
obj98__205.png
obj26__220.png
obj75__320.png
obj4__170.png
obj82__265.png
obj77__165.png
obj50__235.png
obj11__25.png
obj76__165.png
obj51__235.png
obj83__265.png
obj5__170.png
obj92__170.png
obj58__305.png
obj67__270.png
obj40__120.png
obj19__180.png
obj84__50.png
obj12__0.png
obj60__45.png
obj94__50.png
obj66__270.png
obj41__120.png
obj93__170.png
obj59__305.png
obj18__180.png
obj70__45.png
obj56__90.png
obj1__350.png
obj21__245.png
obj72__345.png
obj14__290.png
obj17__60.png
obj61__5.png
obj20__245.png
obj73__345.png
obj15__290.png
obj46__90.png
obj92__15.png
obj31__150.png
obj45__300.png
obj16__200.png
obj97__350.png
obj9__260.png
obj82__15.png
obj8__260.png
obj96__350.png
obj44__300.png
obj30__150.png
obj17__200.png
obj21__60.png
obj74__120.png
obj53__270.png
obj18__155.png
obj81__220.png
obj7__135.png
obj94__85.png
obj70__90.pn

obj86__240.png
obj46__195.png
obj97__155.png
obj29__170.png
obj62__255.png
obj31__355.png
obj45__105.png
obj61__90.png
obj57__280.png
obj85__85.png
obj30__60.png
obj63__255.png
obj44__105.png
obj30__355.png
obj71__90.png
obj96__155.png
obj28__170.png
obj56__280.png
obj20__60.png
obj95__85.png
obj57__45.png
obj24__260.png
obj48__215.png
obj47__45.png
obj49__215.png
obj25__260.png
obj40__325.png
obj34__175.png
obj13__225.png
obj58__100.png
obj26__25.png
obj98__65.png
obj36__25.png
obj88__65.png
obj59__100.png
obj35__175.png
obj41__325.png
obj12__225.png
obj44__25.png
obj79__180.png
obj38__305.png
obj86__320.png
obj3__10.png
obj20__120.png
obj78__180.png
obj21__120.png
obj39__305.png
obj87__320.png
obj54__25.png
obj100__345.png
obj35__45.png
obj69__295.png
obj17__165.png
obj63__335.png
obj30__235.png
obj8__105.png
obj25__45.png
obj9__105.png
obj68__295.png
obj62__335.png
obj16__165.png
obj31__235.png
obj5__215.png
obj91__285.png
obj64__185.png
obj25__300.png
obj51__150.png
obj76__200.png


obj39__60.png
obj100__65.png
obj9__70.png
obj14__10.png
obj49__160.png
obj83__315.png
obj25__115.png
obj51__345.png
obj37__290.png
obj45__0.png
obj50__345.png
obj24__115.png
obj48__160.png
obj82__315.png
obj36__290.png
obj65__70.png
obj59__275.png
obj35__200.png
obj66__300.png
obj12__150.png
obj27__185.png
obj81__65.png
obj34__80.png
obj75__70.png
obj24__80.png
obj34__200.png
obj13__150.png
obj67__300.png
obj58__275.png
obj91__65.png
obj26__185.png
obj81__70.png
obj27__190.png
obj66__315.png
obj12__145.png
obj35__215.png
obj59__260.png
obj34__95.png
obj10__0.png
obj65__65.png
obj24__95.png
obj26__190.png
obj91__70.png
obj58__260.png
obj13__145.png
obj67__315.png
obj34__215.png
obj75__65.png
obj37__285.png
obj25__100.png
obj51__350.png
obj83__300.png
obj49__175.png
obj9__65.png
obj100__70.png
obj36__285.png
obj82__300.png
obj48__175.png
obj50__350.png
obj24__100.png
obj29__75.png
obj97__35.png
obj96__235.png
obj28__210.png
obj44__265.png
obj73__20.png
obj63__135.png
obj8__305.png
obj78_

In [55]:
# print(pix_val[7199])
pix = np.asarray(pix_val)
print(pix[0])

[[53 51 32]
 [53 51 10]
 [29 29 29]
 ...
 [29 29 29]
 [29 29 29]
 [29 29 29]]


In [56]:
pix_out = np.reshape(pix,(7200,128,128,3))

In [51]:
# for a in range(10):
#     file = "out"+str(a)+".txt"
#     with open(file, "w") as text_file:
#     #     text_file.write("i    j    k    l    value \n")
#         for i in range(720):
#             for j in range(128):
#                 for k in range(128):
#                     for l in range(3):
#                         text_file.write("%d    %d    %d    %d    %d \n" % (720*a+i,j,k,l,pix_out[i][j][k][l]))